BRAKES = {

    # ============================================================
    # MECHANICAL / HYDRAULIC
    # ============================================================

    "brake_fluid_bleed": {
        "category": "Brakes",
        "subcategory": "Mechanical / Hydraulic",
        "section": "Brake Fluid Bleeding",
        "fluid": "DOT 3 or DOT 4",
        "capacity": "Approx. 1 L",
        "interval_km": 48000,
        "torque": {"bleeder_plug": "11 N·m (110 kgf·cm, 8 ft·lbf)"},
        "tools": [
            "Brake bleeder",
            "8/10 mm line wrench",
            "Catch bottle",
            "Clear vinyl hose",
            "Techstream scan tool",
            "DLC3 connector"
        ],
        "workflow": [
            "",
            "=== BLEED BRAKE LINE ===",
            "",
            "1. Turn the engine switch on (IG).",
            "2. Remove the brake master cylinder reservoir filler cap assembly.",
            "3. Add brake fluid until the fluid level is between the MIN and MAX lines of the reservoir.",
            "",
            "FRONT RIGHT (RH):",
            "4. Repeatedly depress the brake pedal and bleed air from the bleeder plug of the front disc brake cylinder RH.",
            "5. Repeat the step above until the air is completely bled, and then tighten the bleeder plug while depressing the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "FRONT LEFT (LH):",
            "6. Bleed the air from the bleeder plug of the front disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "REAR RIGHT (RH):",
            "7. With the brake pedal depressed, loosen the bleeder plug of the rear disc brake cylinder RH.",
            "8. Continue to hold the brake pedal and allow brake fluid to be drained from the bleeder plug while the pump motor operates.",
            "",
            "   HINT: Air is bled as the pump motor operates while the brake pedal is being depressed.",
            "   HINT: Be sure to release the brake pedal to stop the motor after approximately 100 seconds of continuous operation.",
            "   HINT: As brake fluid is continuously drained while the pump operates, it is not necessary to repeatedly depress the brake pedal.",
            "",
            "9. When there is no more air in the brake fluid, tighten the bleeder plug, and then release the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "REAR LEFT (LH):",
            "10. Bleed the air from the bleeder plug of the rear disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "11. Turn the engine switch off (IG).",
            "12. Inspect for brake fluid leaks.",
            "13. Check and adjust the brake fluid level (See step 3).",
            "",
            "",
            "=== BLEED BRAKE SYSTEM (with Techstream) ===",
            "",
            "⚠️ WARNING: If air is bled without using the Techstream, damage or accidents may result.",
            "   Therefore, always use the Techstream when bleeding air.",
            "",
            "14. Turn the engine switch on (IG).",
            "15. Remove the brake master cylinder reservoir filler cap assembly.",
            "16. Add brake fluid until the fluid level is between the MIN and MAX lines of the reservoir.",
            "",
            "FRONT RIGHT (RH):",
            "17. Repeatedly depress the brake pedal and bleed air from the bleeder plug of the front disc brake cylinder RH.",
            "18. Repeat the step above until the air is completely bled, and then tighten the bleeder plug while depressing the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "FRONT LEFT (LH):",
            "19. Bleed the air from the bleeder plug of the front disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "REAR RIGHT (RH):",
            "20. With the brake pedal depressed, loosen the bleeder plug of the rear disc brake cylinder RH.",
            "21. Continue to hold the brake pedal and allow brake fluid to be drained from the bleeder plug while the pump motor operates.",
            "",
            "   HINT: Air is bled as the pump motor operates while the brake pedal is being depressed.",
            "   HINT: Be sure to release the brake pedal to stop the motor after approximately 100 seconds of continuous operation.",
            "   HINT: As brake fluid is continuously drained while the pump operates, it is not necessary to repeatedly depress the brake pedal.",
            "",
            "22. When there is no more air in the brake fluid, tighten the bleeder plug, and then release the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "REAR LEFT (LH):",
            "23. Bleed the air from the bleeder plug of the rear disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "=== TECHSSTREAM ABS BLEED ===",
            "",
            "24. Turn the engine switch off and connect the Techstream to the DLC3.",
            "25. Turn the engine switch on (IG).",
            "26. Turn the Techstream on.",
            "27. Enter the following menus: Chassis → ABS/VSC/TRAC → Utility → Air Bleeding.",
            "",
            "   NOTE: To protect the solenoid from overheating, the solenoid operation stops automatically",
            "   in 4 seconds, and then the solenoid will not respond to commands for an additional 20 seconds.",
            "",
            "FRONT RIGHT (FR Line):",
            "28. Repeatedly depress the brake pedal several times, and then, with the brake pedal depressed, turn FR Line on and bleed air.",
            "",
            "   HINT: Air returns to the brake master cylinder reservoir together with the brake fluid",
            "   and is bled from the brake system.",
            "",
            "   NOTE: As it is not possible to visually confirm that air is being bled, repeat this step 10 times.",
            "   NOTE: Do not loosen the bleeder plug.",
            "",
            "FRONT LEFT (FL Line):",
            "29. Turn FL Line on and bleed air using the same procedures as for FR Line.",
            "",
            "REAR RIGHT (RR Line):",
            "30. Turn RR Line on, loosen the bleeder plug of the rear disc brake cylinder RH and drain brake fluid.",
            "",
            "   HINT: Do not depress the brake pedal.",
            "   HINT: As brake fluid is automatically drained while the pump and solenoid operate,",
            "   it is not necessary to operate the brake pedal.",
            "",
            "31. Repeat the step above until the air is completely bled, and then tighten the bleeder plug.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "REAR LEFT (RL Line):",
            "32. Turn RL Line on and bleed air from the bleeder plug of the rear disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "=== FINAL CHECKS ===",
            "",
            "33. Turn the Techstream off and turn the engine switch off.",
            "34. Inspect for brake fluid leaks."
        ]
    }
}