BRAKES = {

    # ============================================================
    # MECHANICAL / HYDRAULIC
    # ============================================================

    "brake_fluid_bleed": {
        "category": "Brakes",
        "subcategory": "Mechanical / Hydraulic",
        "section": "Brake Fluid Bleeding",
        "fluid": "DOT 3 or DOT 4",
        "capacity": "Approx. 1 L",
        "interval_km": 48000,
        "torque": {"bleeder_plug": "11 N·m (110 kgf·cm, 8 ft·lbf)"},
        "tools": [
            "Brake bleeder",
            "8/10 mm line wrench",
            "Catch bottle",
            "Clear vinyl hose",
            "Techstream scan tool",
            "DLC3 connector"
        ],
        "workflow": [
            "",
            "=== BLEED BRAKE LINE ===",
            "",
            "1. Turn the engine switch on (IG).",
            "2. Remove the brake master cylinder reservoir filler cap assembly.",
            "3. Add brake fluid until the fluid level is between the MIN and MAX lines of the reservoir.",
            "",
            "FRONT RIGHT (RH):",
            "4. Repeatedly depress the brake pedal and bleed air from the bleeder plug of the front disc brake cylinder RH.",
            "5. Repeat the step above until the air is completely bled, and then tighten the bleeder plug while depressing the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "FRONT LEFT (LH):",
            "6. Bleed the air from the bleeder plug of the front disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "REAR RIGHT (RH):",
            "7. With the brake pedal depressed, loosen the bleeder plug of the rear disc brake cylinder RH.",
            "8. Continue to hold the brake pedal and allow brake fluid to be drained from the bleeder plug while the pump motor operates.",
            "",
            "   HINT: Air is bled as the pump motor operates while the brake pedal is being depressed.",
            "   HINT: Be sure to release the brake pedal to stop the motor after approximately 100 seconds of continuous operation.",
            "   HINT: As brake fluid is continuously drained while the pump operates, it is not necessary to repeatedly depress the brake pedal.",
            "",
            "9. When there is no more air in the brake fluid, tighten the bleeder plug, and then release the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "REAR LEFT (LH):",
            "10. Bleed the air from the bleeder plug of the rear disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "11. Turn the engine switch off (IG).",
            "12. Inspect for brake fluid leaks.",
            "13. Check and adjust the brake fluid level (See step 3).",
            "",
            "",
            "=== BLEED BRAKE SYSTEM (with Techstream) ===",
            "",
            "⚠️ WARNING: If air is bled without using the Techstream, damage or accidents may result.",
            "   Therefore, always use the Techstream when bleeding air.",
            "",
            "14. Turn the engine switch on (IG).",
            "15. Remove the brake master cylinder reservoir filler cap assembly.",
            "16. Add brake fluid until the fluid level is between the MIN and MAX lines of the reservoir.",
            "",
            "FRONT RIGHT (RH):",
            "17. Repeatedly depress the brake pedal and bleed air from the bleeder plug of the front disc brake cylinder RH.",
            "18. Repeat the step above until the air is completely bled, and then tighten the bleeder plug while depressing the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "FRONT LEFT (LH):",
            "19. Bleed the air from the bleeder plug of the front disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "REAR RIGHT (RH):",
            "20. With the brake pedal depressed, loosen the bleeder plug of the rear disc brake cylinder RH.",
            "21. Continue to hold the brake pedal and allow brake fluid to be drained from the bleeder plug while the pump motor operates.",
            "",
            "   HINT: Air is bled as the pump motor operates while the brake pedal is being depressed.",
            "   HINT: Be sure to release the brake pedal to stop the motor after approximately 100 seconds of continuous operation.",
            "   HINT: As brake fluid is continuously drained while the pump operates, it is not necessary to repeatedly depress the brake pedal.",
            "",
            "22. When there is no more air in the brake fluid, tighten the bleeder plug, and then release the brake pedal.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "REAR LEFT (LH):",
            "23. Bleed the air from the bleeder plug of the rear disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "=== TECHSSTREAM ABS BLEED ===",
            "",
            "24. Turn the engine switch off and connect the Techstream to the DLC3.",
            "25. Turn the engine switch on (IG).",
            "26. Turn the Techstream on.",
            "27. Enter the following menus: Chassis → ABS/VSC/TRAC → Utility → Air Bleeding.",
            "",
            "   NOTE: To protect the solenoid from overheating, the solenoid operation stops automatically",
            "   in 4 seconds, and then the solenoid will not respond to commands for an additional 20 seconds.",
            "",
            "FRONT RIGHT (FR Line):",
            "28. Repeatedly depress the brake pedal several times, and then, with the brake pedal depressed, turn FR Line on and bleed air.",
            "",
            "   HINT: Air returns to the brake master cylinder reservoir together with the brake fluid",
            "   and is bled from the brake system.",
            "",
            "   NOTE: As it is not possible to visually confirm that air is being bled, repeat this step 10 times.",
            "   NOTE: Do not loosen the bleeder plug.",
            "",
            "FRONT LEFT (FL Line):",
            "29. Turn FL Line on and bleed air using the same procedures as for FR Line.",
            "",
            "REAR RIGHT (RR Line):",
            "30. Turn RR Line on, loosen the bleeder plug of the rear disc brake cylinder RH and drain brake fluid.",
            "",
            "   HINT: Do not depress the brake pedal.",
            "   HINT: As brake fluid is automatically drained while the pump and solenoid operate,",
            "   it is not necessary to operate the brake pedal.",
            "",
            "31. Repeat the step above until the air is completely bled, and then tighten the bleeder plug.",
            "   Torque: 11 N·m (110 kgf·cm, 8 ft·lbf)",
            "",
            "REAR LEFT (RL Line):",
            "32. Turn RL Line on and bleed air from the bleeder plug of the rear disc brake cylinder LH using the same procedure as for the RH side.",
            "",
            "=== FINAL CHECKS ===",
            "",
            "33. Turn the Techstream off and turn the engine switch off.",
            "34. Inspect for brake fluid leaks."
        ]
    }
},
"front_brake_pads_removal": {
        "category": "Brakes",
        "subcategory": "Mechanical / Hydraulic",
        "section": "Front Brake Pads - Removal",
        "tools": [
            "Union nut wrench (10 mm flare nut)",
            "Socket set",
            "Brake fluid catch container",
            "Wire brush"
        ],
        "torque": {
            "caliper_bolts": "Refer to installation procedure",
            "lug_nuts": "83 ft·lbf (113 N·m)"
        },
        "sockets": {
            "lug_nuts": "21 mm"
        },
        "workflow": [
            "",
            "=== FRONT BRAKE PADS - REMOVAL ===",
            "",
            "1. REMOVE FRONT WHEEL",
            "",
            "2. DRAIN BRAKE FLUID",
            "   NOTE: Wash off the brake fluid immediately if it comes into contact with a painted surface.",
            "",
            "3. REMOVE FRONT DISC BRAKE PAD KIT",
            "",
            "   a. Remove the pin hold clip.",
            "",
            "      *1  Hole Pin",
            "      *2  Pin Hold Clip",
            "      *3  Anti-rattle Spring",
            "",
            "   NOTE: The pin hold clip can be reused if it has sufficient rebound; no deformation",
            "   or wear; and has had all rust, dirt and foreign matter cleaned off.",
            "",
            "   b. Remove the 2 hole pins.",
            "",
            "   c. Remove the front disc brake anti-rattle spring.",
            "",
            "   NOTE: The anti-rattle spring can be reused if it has sufficient rebound;",
            "   no deformation, cracks or wear; and has had all rust, dirt and foreign matter cleaned off.",
            "",
            "   d. Remove the 2 front disc brake pads from the disc brake cylinder.",
            "",
            "   e. Remove the front anti-squeal shims from the front disc brake pads.",
            "",
            "4. REMOVE DISC BRAKE CYLINDER ASSEMBLY LH",
            "",
            "   a. Using a union nut wrench, disconnect the brake tube from the disc brake cylinder assembly.",
            "",
            "   HINT: Use a container to catch brake fluid as it drains out.",
            "",
            "   b. Remove the 2 bolts and disc brake cylinder assembly.",
            "",
            "5. REMOVE FRONT DISC",
            "",
            "   a. Place matchmarks on the disc and axle hub if planning to reuse the disc.",
            "",
            "      *1  Matchmark",
            "",
            "   b. Remove the front disc."
        ]
    },
    "front_brake_inspection": {
        "category": "Brakes",
        "subcategory": "Mechanical / Hydraulic",
        "section": "Front Brake - Inspection",
        "tools": [
            "Ruler",
            "Micrometer",
            "Dial indicator",
            "Socket set",
            "Torque wrench"
        ],
        "torque": {
            "hub_nuts_aluminum_wheel": "103 N·m (1050 kgf·cm, 76 ft·lbf)",
            "hub_nuts_steel_wheel": "112 N·m (1142 kgf·cm, 83 ft·lbf)"
        },
        "specs": {
            "pad_standard_thickness": "11.3 mm (0.445 in.)",
            "pad_minimum_thickness": "1.0 mm (0.0394 in.)",
            "disc_standard_thickness": "32.0 mm (1.26 in.)",
            "disc_minimum_thickness": "29.0 mm (1.14 in.)",
            "maximum_disc_runout": "0.05 mm (0.00197 in.)",
            "runout_measurement_point": "10 mm (0.394 in.) from outer edge"
        },
        "workflow": [
            "",
            "=== FRONT BRAKE - INSPECTION ===",
            "",
            "1. CHECK BRAKE CYLINDER AND PISTON",
            "",
            "   a. Check the cylinder bore and piston for rust or scoring.",
            "   b. If necessary, replace the disc brake cylinder assembly.",
            "",
            "2. CHECK PAD LINING THICKNESS",
            "",
            "   a. Using a ruler, measure the pad lining thickness.",
            "",
            "   Standard thickness: 11.3 mm (0.445 in.)",
            "   Minimum thickness:  1.0 mm (0.0394 in.)",
            "",
            "   b. If the pad lining thickness is less than the minimum, replace the pad.",
            "",
            "3. CHECK DISC THICKNESS",
            "",
            "   a. Using a micrometer, measure the disc thickness.",
            "",
            "   Standard thickness: 32.0 mm (1.26 in.)",
            "   Minimum thickness:  29.0 mm (1.14 in.)",
            "",
            "   b. If the disc thickness is less than the minimum, replace the disc.",
            "",
            "4. CHECK DISC RUNOUT",
            "",
            "   a. Install the disc with the 6 hub nuts.",
            "",
            "      For aluminum wheel: 103 N·m (1050 kgf·cm, 76 ft·lbf)",
            "      For steel wheel:    112 N·m (1142 kgf·cm, 83 ft·lbf)",
            "",
            "   b. Using a dial indicator, measure the disc runout 10 mm (0.394 in.)",
            "      from the outer edge of the disc.",
            "",
            "   Maximum disc runout: 0.05 mm (0.00197 in.)",
            "",
            "   c. If the disc runout is more than the maximum:",
            "      - Check the bearing play in the axial direction",
            "      - Check the axle hub runout (Refer to Step 6)",
            "      - If bearing play and axle hub runout are normal, adjust the disc runout",
            "        or grind the disc using an 'On-car' brake lathe.",
            "",
            "   d. Remove the 6 hub nuts and disc."
        ]
    },
    "front_brake_pads_installation": {
        "category": "Brakes",
        "subcategory": "Mechanical / Hydraulic",
        "section": "Front Brake Pads - Installation",
        "tools": [
            "Union nut wrench (10 mm flare nut)",
            "Torque wrench",
            "Brake shim grease (Part No. 08887-80409 or equivalent)"
        ],
        "torque": {
            "caliper_mounting_bolts": "185 N·m (1887 kgf·cm, 137 ft·lbf)",
            "brake_tube_union": "15 N·m (155 kgf·cm, 11 ft·lbf)"
        },
        "workflow": [
            "",
            "=== FRONT BRAKE PADS - INSTALLATION ===",
            "",
            "1. INSTALL FRONT DISC",
            "",
            "   a. Align the matchmarks and install the front disc.",
            "",
            "   HINT: When replacing the disc with a new one, select the installation position",
            "   where the disc has the smallest runout.",
            "",
            "2. INSTALL DISC BRAKE CYLINDER ASSEMBLY LH",
            "",
            "   a. Install the disc brake cylinder assembly with the 2 bolts.",
            "      Torque: 185 N·m (1887 kgf·cm, 137 ft·lbf)",
            "",
            "   b. Using a union nut wrench, connect the brake tube to the disc brake cylinder assembly.",
            "      Torque: 15 N·m (155 kgf·cm, 11 ft·lbf)",
            "",
            "3. INSTALL FRONT ANTI-SQUEAL SHIM KIT",
            "",
            "   NOTE: When replacing the front disc brake pads with new ones, make sure to replace",
            "   the front anti-squeal shim kit at the same time.",
            "   NOTE: Do not apply lubricants to the lining surface of the brake pad.",
            "   NOTE: Install the front anti-squeal shims in the correct position and direction.",
            "",
            "   a. Install the front anti-squeal shims to the front disc brake pads.",
            "",
            "   NOTE: There should be no oil or grease on the friction surfaces of the front disc",
            "   brake pads and the front disc.",
            "",
            "4. INSTALL FRONT DISC BRAKE PAD KIT",
            "",
            "   NOTE: There should be no oil or grease on the friction surfaces of the front disc",
            "   brake pads and the front disc.",
            "",
            "   a. Lightly apply brake shim grease (Part No. 08887-80409) or equivalent to the areas",
            "      shown in the illustration where the front disc brake pad and disc brake cylinder",
            "      assembly contact each other.",
            "",
            "      Grease application areas:",
            "      *a  2.0 mm (0.0787 in.)",
            "      *b  3.0 mm (0.1181 in.)",
            "      *c  10 mm (0.3937 in.)",
            "",
            "   b. Install the 2 front disc brake pads to the disc brake cylinder.",
            "",
            "   c. Install the anti-rattle spring between the 2 front disc brake pads.",
            "",
            "   NOTE: The anti-rattle spring can be reused if it has sufficient rebound;",
            "   no deformation, cracks or wear; and has had all rust, dirt and foreign matter",
            "   cleaned off.",
            "",
            "   d. Install the 2 hole pins.",
            "",
            "   e. Install the pin hold clip.",
            "",
            "   NOTE: The pin hold clip can be reused if it has sufficient rebound;",
            "   no deformation or wear; and has had all rust, dirt and foreign matter cleaned off.",
            "",
            "5. BLEED BRAKE LINE",
            "",
            "   Refer to Brake Fluid Bleeding procedure."
        ]
    },
    "rear_brake_pads_removal": {
        "category": "Brakes",
        "subcategory": "Mechanical / Hydraulic",
        "section": "Rear Brake Pads - Removal",
        "tools": [
            "Union nut wrench",
            "Socket set",
            "Brake fluid catch container",
            "Flathead screwdriver (for shoe adjuster)"
        ],
        "torque": {
            "union_bolt": "Refer to installation procedure"
        },
        "workflow": [
            "",
            "=== REAR BRAKE PADS - REMOVAL ===",
            "",
            "1. REMOVE REAR WHEEL",
            "",
            "2. DRAIN BRAKE FLUID",
            "",
            "   NOTE: Wash the brake fluid off immediately if it adheres to any painted surfaces.",
            "",
            "3. DISCONNECT REAR FLEXIBLE HOSE LH",
            "",
            "   a. Remove the union bolt and gasket from the rear disc brake cylinder, and then",
            "      disconnect the rear flexible hose from the rear disc brake cylinder.",
            "",
            "   HINT: Use a container to catch brake fluid as it drains out.",
            "",
            "4. REMOVE REAR DISC BRAKE CYLINDER ASSEMBLY LH",
            "",
            "   a. Remove the 2 cylinder slide pins from the rear disc brake cylinder.",
            "   b. Remove the rear disc brake cylinder from the rear disc brake cylinder mounting.",
            "",
            "5. REMOVE REAR DISC BRAKE PAD",
            "",
            "   a. Remove the 2 rear disc brake pads together with the rear disc brake anti-squeal",
            "      shims from the rear disc brake cylinder mounting.",
            "",
            "6. REMOVE REAR DISC BRAKE ANTI-SQUEAL SHIM",
            "",
            "   a. Remove the 2 rear disc brake anti-squeal shims from the rear disc brake pads.",
            "",
            "7. REMOVE REAR DISC BRAKE PAD WEAR INDICATOR PLATE",
            "",
            "   a. Remove the rear disc brake pad wear indicator plate from the inner disc brake pad.",
            "",
            "8. REMOVE REAR NO. 1 DISC BRAKE PAD SUPPORT PLATE",
            "",
            "   NOTE: If it is necessary to remove the pad support plates, replace them with new ones.",
            "",
            "   a. Remove the 2 pad support plates from the rear disc brake cylinder mounting.",
            "",
            "9. REMOVE REAR NO. 2 DISC BRAKE PAD SUPPORT PLATE",
            "",
            "   NOTE: If it is necessary to remove the pad support plates, replace them with new ones.",
            "",
            "   a. Remove the 2 pad support plates from the rear disc brake cylinder mounting.",
            "",
            "10. REMOVE REAR DISC BRAKE CYLINDER MOUNTING LH",
            "",
            "   a. Remove the 2 bolts, 2 plate washers and rear disc brake cylinder mounting.",
            "",
            "11. REMOVE REAR DISC BRAKE BUSH DUST BOOT",
            "",
            "   a. Remove the rear disc brake bush dust boot from the rear disc brake cylinder mounting.",
            "",
            "12. REMOVE REAR DISC BRAKE CYLINDER SLIDE BUSH",
            "",
            "   a. Remove the rear disc brake cylinder slide bush from the rear disc brake cylinder mounting.",
            "",
            "13. REMOVE REAR DISC BRAKE CYLINDER HOLE PLUG",
            "",
            "   a. Remove the rear disc brake cylinder hole plug from the rear disc brake cylinder mounting.",
            "",
            "14. REMOVE REAR DISC",
            "",
            "   a. Put matchmarks on the rear disc and axle hub if planning to reuse the disc.",
            "",
            "      *1  Matchmark",
            "",
            "   b. Turn the shoe adjuster until the disc turns freely, and then remove the disc.",
            "",
            "      ← Shoe Adjuster Contracts",
            "      → Shoe Adjuster Expands",
            "",
            "   c. Remove the rear disc."
        ]
    },
    "rear_brake_inspection": {
        "category": "Brakes",
        "subcategory": "Mechanical / Hydraulic",
        "section": "Rear Brake - Inspection",
        "tools": [
            "Ruler",
            "Micrometer",
            "Dial indicator",
            "Socket set",
            "Torque wrench"
        ],
        "torque": {
            "hub_nuts_aluminum_wheel": "103 N·m (1050 kgf·cm, 76 ft·lbf)",
            "hub_nuts_steel_wheel": "112 N·m (1142 kgf·cm, 83 ft·lbf)"
        },
        "specs": {
            "pad_standard_thickness": "10.0 mm (0.394 in.)",
            "pad_minimum_thickness": "1.0 mm (0.0394 in.)",
            "disc_standard_thickness": "18.0 mm (0.709 in.)",
            "disc_minimum_thickness": "16.0 mm (0.630 in.)",
            "maximum_disc_runout": "0.20 mm (0.00787 in.)",
            "runout_measurement_point": "10 mm (0.394 in.) from outer edge"
        },
        "workflow": [
            "",
            "=== REAR BRAKE - INSPECTION ===",
            "",
            "1. CHECK PAD LINING THICKNESS",
            "",
            "   a. Using a ruler, measure the pad lining thickness.",
            "",
            "   Standard thickness: 10.0 mm (0.394 in.)",
            "   Minimum thickness:  1.0 mm (0.0394 in.)",
            "",
            "   b. If the pad lining thickness is less than the minimum, replace the pad.",
            "",
            "2. CHECK DISC THICKNESS",
            "",
            "   a. Using a micrometer, measure the disc thickness.",
            "",
            "   Standard thickness: 18.0 mm (0.709 in.)",
            "   Minimum thickness:  16.0 mm (0.630 in.)",
            "",
            "   b. If the disc thickness is less than the minimum, replace the disc.",
            "",
            "3. CHECK DISC RUNOUT",
            "",
            "   a. Install the disc with the 6 hub nuts.",
            "",
            "      For aluminum wheel: 103 N·m (1050 kgf·cm, 76 ft·lbf)",
            "      For steel wheel:    112 N·m (1142 kgf·cm, 83 ft·lbf)",
            "",
            "   b. Using a dial indicator, measure the disc runout 10 mm (0.394 in.)",
            "      from the outer edge of the disc.",
            "",
            "   Maximum disc runout: 0.20 mm (0.00787 in.)",
            "",
            "   c. If the disc runout is more than the maximum:",
            "      - Check the rear axle shaft (Refer to Step 1)",
            "      - If the rear axle shaft is normal, adjust the disc runout",
            "        or grind the disc using an on-vehicle brake lathe.",
            "",
            "4. ADJUST DISC RUNOUT",
            "",
            "   a. Remove the 2 bolts and rear disc brake cylinder mounting from the backing plate.",
            "",
            "   b. Remove the hub nuts and disc.",
            "",
            "   c. Rotate the disc 1/5 of a turn from its original position on the hub and",
            "      install the disc with the hub nuts.",
            "",
            "      For aluminum wheel: 103 N·m (1050 kgf·cm, 76 ft·lbf)",
            "      For steel wheel:    112 N·m (1142 kgf·cm, 83 ft·lbf)",
            "",
            "   d. Measure the disc runout. Make a note of the runout and the disc position on the hub.",
            "",
            "   e. Repeat steps c and d until the disc has been installed on the 3 remaining hub positions.",
            "",
            "   f. If the minimum runout recorded above is less than 0.20 mm (0.00787 in.),",
            "      install the disc in that position.",
            "",
            "   g. If the minimum runout recorded above is more than 0.20 mm (0.00787 in.),",
            "      replace the disc and repeat the 'Check Disc Runout' procedure."
        ]
    },
    
    