ENGINE_MECHANICAL = {

    "engine_oil_filter": {
        "category": "Engine Mechanical",
        "subcategory": "Oil & Filter",
        "section": "Engine Oil & Filter Replacement",
        "fluid": {
            "type": "ILSAC multigrade engine oil",
            "viscosity": "0W-20",
            "capacity": {
                "drain_refill_without_filter": "5.7 L (6.0 US qts, 5.0 Imp. qts)",
                "drain_refill_with_filter": "6.2 L (6.6 US qts, 5.5 Imp. qts)",
                "dry_fill": "7.1 L (7.5 US qts, 6.2 Imp. qts)"
            }
        },
        "torque": {
            "oil_pan_drain_plug": "40 N·m (408 kgf·cm, 30 ft·lbf)",
            "oil_filter_cap": "25 N·m (255 kgf·cm, 18 ft·lbf)",
            "oil_filter_drain_plug": "13 N·m (127 kgf·cm, 9 ft·lbf)",
            "engine_under_cover_bolts": "29 N·m (296 kgf·cm, 21 ft·lbf)",
            "front_lower_bumper_cover_bolts": "8.0 N·m (82 kgf·cm, 71 in·lbf)"
        },
        "tools": [
            "SST 09228-06501 (oil filter wrench)",
            "15 mm inside diameter hose",
            "Torque wrench",
            "Socket set",
            "Oil drain pan",
            "Funnel",
            "New gasket (drain plug)",
            "New O-rings (filter cap & drain plug)"
        ],
        "workflow": [
            "",
            "=== ENGINE OIL & FILTER REPLACEMENT ===",
            "",
            "1. REMOVE ENGINE UNDER COVER SEAL",
            "",
            "   a. Remove the 2 bolts and engine under cover seal.",
            "",
            "2. REMOVE COOL AIR INTAKE DUCT (for 4WD with Intuitive Parking Assist System)",
            "",
            "   Refer to procedure for your model year.",
            "",
            "3. DISCONNECT FRONT LOWER BUMPER COVER",
            "",
            "   a. Remove the 2 bolts and clip, and disconnect the front bumper lower cover.",
            "",
            "4. DISCONNECT NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "",
            "   a. Remove the 4 bolts and open the No. 1 engine under cover sub-assembly",
            "      as shown in the illustration.",
            "",
            "5. DRAIN ENGINE OIL",
            "",
            "   a. Remove the oil filler cap.",
            "   b. Remove the oil pan drain plug and drain the engine oil into a container.",
            "   c. Install a new gasket and the oil pan drain plug.",
            "      Torque: 40 N·m (408 kgf·cm, 30 ft·lbf)",
            "",
            "6. REMOVE OIL FILTER ELEMENT",
            "",
            "   a. Connect a hose with an inside diameter of 15 mm (0.591 in.) to the pipe.",
            "",
            "      *1  Pipe",
            "      *2  Hose",
            "",
            "   b. Remove the oil filter drain plug.",
            "",
            "   c. Install the pipe to the oil filter cap.",
            "",
            "      *1  Oil Filter Cap Assembly",
            "      *2  Valve",
            "      *3  Pipe",
            "      *4  O-ring",
            "      *5  Hose",
            "",
            "   NOTE: If the O-ring is removed with the drain plug, install the O-ring",
            "   together with the pipe.",
            "",
            "   HINT: Use a container to catch the draining oil.",
            "",
            "   d. Check that oil is drained from the oil filter. Then, disconnect the pipe",
            "      and remove the O-ring as shown in the illustration.",
            "",
            "   e. Using SST, remove the oil filter cap.",
            "      SST: 09228-06501",
            "",
            "      *1  Oil Filter Bracket Clip",
            "",
            "   NOTE: Do not remove the oil filter bracket clip.",
            "",
            "   f. Remove the oil filter element and O-ring from the oil filter cap.",
            "",
            "      *1  O-ring",
            "",
            "   NOTE: Be sure to remove the O-ring (for the cap) by hand, without using any",
            "   tools, to prevent damage to the groove for the O-ring in the cap.",
            "",
            "7. INSTALL OIL FILTER ELEMENT",
            "",
            "   a. Clean the inside of the oil filter cap, the threads and O-ring groove.",
            "",
            "   b. Apply a small amount of engine oil to a new O-ring and install the O-ring",
            "      to the oil filter cap.",
            "",
            "      *1  O-ring",
            "      *a  CORRECT",
            "      *b  INCORRECT",
            "",
            "   NOTE: Be sure to install the O-ring in the proper location, otherwise oil may leak.",
            "   NOTE: Do not twist the O-ring.",
            "",
            "   c. Set a new oil filter element on the oil filter cap.",
            "",
            "   d. Remove any dirt or foreign matter from the installation surface of the engine.",
            "",
            "   e. Apply a small amount of engine oil to the O-ring again and temporarily install",
            "      the oil filter cap.",
            "",
            "   NOTE: Do not pinch the O-ring for the cap.",
            "",
            "   f. Using SST, tighten the oil filter cap.",
            "      SST: 09228-06501",
            "      Torque: 25 N·m (255 kgf·cm, 18 ft·lbf)",
            "",
            "      *1  Oil Filter Cap Assembly",
            "      *2  O-ring",
            "      *3  Oil Filter Bracket",
            "      *4  Oil Filter Bracket Clip",
            "      *a  No gap",
            "",
            "   NOTE: After tightening the oil filter cap assembly, make sure that there is",
            "   no gap and that the O-ring is not protruding.",
            "   NOTE: When tightening the oil filter cap, do not remove the oil filter bracket clip.",
            "",
            "   g. Apply a small amount of engine oil to a new drain plug O-ring and install",
            "      the O-ring to the oil filter cap.",
            "",
            "      *1  O-Ring",
            "",
            "   NOTE: Before installing the O-ring, remove any dirt or foreign matter from",
            "   the installation surface of the oil filter cap.",
            "",
            "   h. Install the oil filter drain plug.",
            "      Torque: 13 N·m (127 kgf·cm, 9 ft·lbf)",
            "",
            "   NOTE: Make sure that the O-ring does not get caught between the parts.",
            "",
            "8. ADD ENGINE OIL",
            "",
            "   a. Add fresh engine oil.",
            "",
            "   NOTE: Do not allow engine oil to adhere to the moving parts of the belt",
            "   tensioner, as this may cause malfunctions.",
            "   If engine oil is on the location indicated by the arrow, replace the belt",
            "   tensioner.",
            "",
            "   Standard Engine Oil:",
            "   Oil Grade: ILSAC multigrade engine oil",
            "   Oil Viscosity (SAE): 0W-20",
            "",
            "   Standard Oil Capacity:",
            "   Drain and refill without oil filter change:  5.7 L (6.0 US qts, 5.0 Imp. qts)",
            "   Drain and refill with oil filter change:     6.2 L (6.6 US qts, 5.5 Imp. qts)",
            "   Dry fill:                                     7.1 L (7.5 US qts, 6.2 Imp. qts)",
            "",
            "9. CHECK ENGINE OIL LEVEL",
            "",
            "   Refer to Step 2",
            "",
            "10. INSPECT FOR ENGINE OIL LEAK",
            "",
            "   a. Start the engine. Make sure that there are no oil leaks from the area that",
            "      was worked on.",
            "",
            "11. CONNECT NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "",
            "   a. Close the No. 1 engine under cover sub-assembly with the 4 bolts.",
            "      Torque: 29 N·m (296 kgf·cm, 21 ft·lbf)",
            "",
            "12. CONNECT FRONT LOWER BUMPER COVER",
            "",
            "   a. Connect the front lower bumper cover with the 2 bolts and clip.",
            "      Torque: 8.0 N·m (82 kgf·cm, 71 in·lbf)",
            "",
            "13. INSTALL COOL AIR INTAKE DUCT (for 4WD with Intuitive Parking Assist System)",
            "",
            "   Refer to procedure for your model year.",
            "",
            "14. INSTALL ENGINE UNDER COVER SEAL",
            "",
            "   a. Install the engine under cover seal with the 2 bolts.",
            "      Torque: 29 N·m (296 kgf·cm, 21 ft·lbf)"
        ]
    },
    "coolant_replacement": {
        "category": "Engine Mechanical",
        "subcategory": "Cooling System",
        "section": "Engine Coolant Replacement",
        "fluid": {
            "type": "Toyota SLLC or similar high quality ethylene glycol based non-silicate, non-amine, non-nitrite, non-borate coolant with long-life hybrid organic acid technology",
            "capacity": "10.5 L (11.1 US qts, 9.2 Imp. qts)"
        },
        "torque": {
            "cylinder_block_drain_cock_plug": "13 N·m (130 kgf·cm, 9 ft·lbf)"
        },
        "tools": [
            "Coolant drain pan",
            "Funnel",
            "Protective gloves"
        ],
        "references": {
            "upper_radiator_support_seal": "Upper Radiator Support Seal",
            "engine_under_cover": "No. 1 Engine Under Cover",
            "rear_engine_under_cover": "Rear Engine Under Cover",
            "front_lower_bumper_cover": "Front Lower Bumper Cover",
            "cool_air_intake_duct": "Cool Air Intake Duct"
        },
        "workflow": [
            "",
            "=== ENGINE COOLANT REPLACEMENT ===",
            "",
            "1. REMOVE UPPER RADIATOR SUPPORT SEAL",
            "   → Refer to Upper Radiator Support Seal Removal",
            "",
            "2. REMOVE COOL AIR INTAKE DUCT (for 4WD with Intuitive Parking Assist System)",
            "   → Refer to Cool Air Intake Duct Removal",
            "",
            "3. REMOVE FRONT LOWER BUMPER COVER",
            "   → Refer to Front Lower Bumper Cover Removal",
            "",
            "4. REMOVE AIR INTAKE DUCT LH (w/ Intuitive Parking Assist System)",
            "   → Refer to Air Intake Duct LH Removal",
            "",
            "5. REMOVE AIR INTAKE DUCT RH (w/ Intuitive Parking Assist System)",
            "   → Refer to Air Intake Duct RH Removal",
            "",
            "6. REMOVE NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "   → Refer to No. 1 Engine Under Cover Removal",
            "",
            "7. REMOVE REAR ENGINE UNDER COVER ASSEMBLY",
            "   → Refer to Rear Engine Under Cover Removal",
            "",
            "8. DRAIN ENGINE COOLANT",
            "",
            "   ⚠️ WARNING: Do not remove the radiator cap while the engine and radiator",
            "   are still hot. Pressurized, hot engine coolant and steam may be released",
            "   and cause serious burns.",
            "",
            "   a. Loosen the radiator drain cock plug.",
            "",
            "      *1  Reservoir Cap",
            "      *2  Radiator Cap",
            "      *3  Radiator Drain Cock Plug",
            "      *4  Cylinder Block Drain Cock Plug (RH side)",
            "",
            "   b. Remove the radiator cap and drain the coolant.",
            "",
            "   HINT: Collect the coolant in a container and dispose of it according to",
            "   the regulations in your area.",
            "",
            "   c. Loosen the cylinder block drain cock plug and drain the coolant from",
            "      the engine.",
            "",
            "9. ADD ENGINE COOLANT",
            "",
            "   a. Tighten the cylinder block drain cock plug.",
            "      Torque: 13 N·m (130 kgf·cm, 9 ft·lbf)",
            "",
            "   b. Tighten the radiator drain cock plug by hand.",
            "",
            "   c. Add engine coolant.",
            "",
            "   Standard Capacity: 10.5 L (11.1 US qts, 9.2 Imp. qts)",
            "",
            "   NOTE: Do not substitute plain water for engine coolant.",
            "",
            "   HINT: TOYOTA vehicles are filled with TOYOTA SLLC at the factory.",
            "   Only use TOYOTA SLLC or similar high quality ethylene glycol based",
            "   non-silicate, non-amine, non-nitrite, non-borate coolant with long-life",
            "   hybrid organic acid technology.",
            "",
            "   d. Press the No. 1 and No. 2 radiator hoses several times by hand,",
            "      and then check the coolant level. If low, add coolant.",
            "",
            "   e. Slowly pour coolant into the radiator reservoir until it reaches",
            "      the F line.",
            "   f. Install the reservoir cap.",
            "   g. Install the radiator cap.",
            "",
            "   h. Start the engine and stop it immediately.",
            "   i. Allow approximately 10 seconds to pass. Then remove the radiator cap",
            "      and check the coolant level. If decreased, add coolant.",
            "   j. Repeat steps g, h, i until the coolant level does not decrease.",
            "",
            "   HINT: Perform this step while the engine is cold, as air in the No. 1",
            "   radiator hose will flow into the radiator if warmed up and thermostat opens.",
            "",
            "   k. Install the radiator cap.",
            "",
            "   l. Set the air conditioning as follows:",
            "      - Fan speed: Any setting except off",
            "      - Temperature: Toward WARM",
            "      - A/C switch: Off",
            "",
            "   m. Start the engine, warm it up until the thermostat opens, and then",
            "      continue to run for several minutes to circulate the coolant.",
            "",
            "   ⚠️ WARNING:",
            "   - Wear protective gloves. Hot areas on the parts may injure your hands.",
            "   - Be careful of the fan.",
            "   - Be careful as the engine, radiator and radiator hoses are hot.",
            "",
            "   NOTE:",
            "   - If radiator reservoir is empty after starting, stop engine, wait",
            "     until coolant has cooled, and add coolant to F line.",
            "   - Do not start engine when there is no coolant in the reservoir.",
            "   - Watch engine coolant temperature gauge — do not overheat.",
            "",
            "   HINT: Press No. 1 and No. 2 radiator hoses several times by hand",
            "   to bleed air while warming up. Thermostat opening confirmed by",
            "   pressing No. 2 radiator hose and feeling coolant flow.",
            "",
            "   n. Stop engine, wait until coolant cools to ambient temperature.",
            "      Remove radiator cap and check coolant level.",
            "",
            "   ⚠️ WARNING: Do not remove radiator cap while engine and radiator",
            "   are still hot.",
            "",
            "   o. If coolant level has decreased, add coolant and warm up engine",
            "      until thermostat opens.",
            "   p. If coolant level has not decreased, check reservoir is at F line.",
            "   q. If below F line, repeat steps k through p.",
            "   r. If above F line, drain coolant until level reaches F line.",
            "",
            "10. INSPECT FOR ENGINE COOLANT LEAK",
            "    → Refer to Coolant Leak Inspection",
            "",
            "11. INSTALL REAR ENGINE UNDER COVER ASSEMBLY",
            "    → Refer to Rear Engine Under Cover Installation",
            "",
            "12. INSTALL NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "    → Refer to No. 1 Engine Under Cover Installation",
            "",
            "13. INSTALL FRONT LOWER BUMPER COVER",
            "    → Refer to Front Lower Bumper Cover Installation",
            "",
            "14. INSTALL AIR INTAKE DUCT LH (w/ Intuitive Parking Assist System)",
            "    → Refer to Air Intake Duct LH Installation",
            "",
            "15. INSTALL AIR INTAKE DUCT RH (w/ Intuitive Parking Assist System)",
            "    → Refer to Air Intake Duct RH Installation",
            "",
            "16. INSTALL COOL AIR INTAKE DUCT (for 4WD with Intuitive Parking Assist System)",
            "    → Refer to Cool Air Intake Duct Installation",
            "",
            "17. INSTALL UPPER RADIATOR SUPPORT SEAL",
            "    → Refer to Upper Radiator Support Seal Installation"
        ]
    },
    "upper_radiator_support_seal_removal": {
        "category": "Engine Mechanical",
        "subcategory": "Cooling System",
        "section": "Upper Radiator Support Seal - Removal",
        "tools": ["Clip remover or flathead screwdriver"],
        "workflow": [
            "",
            "=== UPPER RADIATOR SUPPORT SEAL - REMOVAL ===",
            "",
            "1. REMOVE UPPER RADIATOR SUPPORT SEAL",
            "",
            "   a. Remove the 13 clips and upper radiator support seal."
        ]
    },
    "cool_air_intake_duct_removal": {
        "category": "Engine Mechanical",
        "subcategory": "Air Intake",
        "section": "Cool Air Intake Duct - Removal (4WD)",
        "tools": ["Clip remover or flathead screwdriver"],
        "workflow": [
            "",
            "=== COOL AIR INTAKE DUCT - REMOVAL (4WD) ===",
            "",
            "1. REMOVE COOL AIR INTAKE DUCT",
            "",
            "   a. Remove the 4 clips and cool air intake duct."
        ]
    },
    "front_lower_bumper_cover_removal": {
        "category": "Engine Mechanical",
        "subcategory": "Body",
        "section": "Front Lower Bumper Cover - Removal (w/o Intuitive Parking Assist)",
        "tools": [
            "Clip remover",
            "Socket set"
        ],
        "workflow": [
            "",
            "=== FRONT LOWER BUMPER COVER - REMOVAL ===",
            "",
            "1. REMOVE FRONT LOWER BUMPER COVER",
            "",
            "   a. Remove the clip, 5 bolts and front lower bumper cover."
        ]
    },
    "no1_engine_under_cover_removal": {
        "category": "Engine Mechanical",
        "subcategory": "Under Covers",
        "section": "No. 1 Engine Under Cover - Removal",
        "tools": ["Socket set"],
        "workflow": [
            "",
            "=== NO. 1 ENGINE UNDER COVER - REMOVAL ===",
            "",
            "1. REMOVE NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "",
            "   a. Remove the 4 bolts.",
            "   b. Unhook the No. 1 engine under cover sub-assembly from the",
            "      vehicle body as shown in the illustration."
        ]
    },
    "rear_engine_under_cover_removal": {
        "category": "Engine Mechanical",
        "subcategory": "Under Covers",
        "section": "Rear Engine Under Cover - Removal",
        "tools": ["Socket set"],
        "workflow": [
            "",
            "=== REAR ENGINE UNDER COVER - REMOVAL ===",
            "",
            "1. REMOVE REAR ENGINE UNDER COVER ASSEMBLY",
            "",
            "   a. Remove the 4 bolts and rear engine under cover assembly."
        ]
    },
    "coolant_leak_inspection": {
        "category": "Engine Mechanical",
        "subcategory": "Cooling System",
        "section": "Coolant Leak - On-Vehicle Inspection",
        "tools": [
            "Radiator cap tester",
            "Engine coolant"
        ],
        "specs": {
            "test_pressure": "123 kPa (1.3 kgf/cm², 18 psi)"
        },
        "workflow": [
            "",
            "=== COOLANT LEAK - ON-VEHICLE INSPECTION ===",
            "",
            "1. INSPECT FOR COOLANT LEAK",
            "",
            "   ⚠️ WARNING: To avoid being burned, do not remove the radiator",
            "   reservoir cap while the engine and radiator are still hot.",
            "   Thermal expansion may cause hot engine coolant and steam",
            "   to blow out from the radiator.",
            "",
            "   a. Fill the radiator with engine coolant, and then attach a",
            "      radiator cap tester.",
            "   b. Warm up the engine.",
            "   c. Using the radiator cap tester, increase the pressure inside",
            "      the radiator to 123 kPa (1.3 kgf/cm², 18 psi), and then",
            "      check that the pressure does not drop.",
            "",
            "   d. If the pressure drops, check the hoses, radiator and water",
            "      pump for leakage.",
            "   e. If there are no signs or traces of external engine coolant",
            "      leakage, check the heater core, cylinder block and head."
        ]
    },
    "rear_engine_under_cover_installation": {
        "category": "Engine Mechanical",
        "subcategory": "Under Covers",
        "section": "Rear Engine Under Cover - Installation",
        "torque": {
            "bolts": "29 N·m (296 kgf·cm, 21 ft·lbf)"
        },
        "tools": [
            "Socket set",
            "Torque wrench"
        ],
        "workflow": [
            "",
            "=== REAR ENGINE UNDER COVER - INSTALLATION ===",
            "",
            "1. INSTALL REAR ENGINE UNDER COVER ASSEMBLY",
            "",
            "   a. Install the rear engine under cover assembly with the 4 bolts.",
            "      Torque: 29 N·m (296 kgf·cm, 21 ft·lbf)"
        ]
    },
    "no1_engine_under_cover_installation": {
        "category": "Engine Mechanical",
        "subcategory": "Under Covers",
        "section": "No. 1 Engine Under Cover - Installation",
        "torque": {
            "bolts": "29 N·m (296 kgf·cm, 21 ft·lbf)"
        },
        "tools": [
            "Socket set",
            "Torque wrench"
        ],
        "workflow": [
            "",
            "=== NO. 1 ENGINE UNDER COVER - INSTALLATION ===",
            "",
            "1. INSTALL NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "",
            "   a. Hook the No. 1 engine under cover sub-assembly to the",
            "      vehicle body as shown in the illustration.",
            "   b. Install the 4 bolts.",
            "      Torque: 29 N·m (296 kgf·cm, 21 ft·lbf)"
        ]
    },
    "front_lower_bumper_cover_installation": {
        "category": "Engine Mechanical",
        "subcategory": "Body",
        "section": "Front Lower Bumper Cover - Installation (w/o Intuitive Parking Assist)",
        "torque": {
            "bolts": "8.0 N·m (82 kgf·cm, 71 in·lbf)"
        },
        "tools": [
            "Socket set",
            "Torque wrench"
        ],
        "workflow": [
            "",
            "=== FRONT LOWER BUMPER COVER - INSTALLATION ===",
            "",
            "1. INSTALL FRONT LOWER BUMPER COVER",
            "",
            "   a. Install the front bumper cover lower with the 5 bolts and clip.",
            "      Torque: 8.0 N·m (82 kgf·cm, 71 in·lbf)"
        ]
    },
    "cool_air_intake_duct_installation": {
        "category": "Engine Mechanical",
        "subcategory": "Air Intake",
        "section": "Cool Air Intake Duct - Installation (4WD)",
        "tools": ["None"],
        "workflow": [
            "",
            "=== COOL AIR INTAKE DUCT - INSTALLATION (4WD) ===",
            "",
            "1. INSTALL COOL AIR INTAKE DUCT",
            "",
            "   a. Install the cool air intake duct with the 4 clips."
        ]
    },
    "upper_radiator_support_seal_installation": {
        "category": "Engine Mechanical",
        "subcategory": "Cooling System",
        "section": "Upper Radiator Support Seal - Installation",
        "tools": ["None"],
        "workflow": [
            "",
            "=== UPPER RADIATOR SUPPORT SEAL - INSTALLATION ===",
            "",
            "1. INSTALL UPPER RADIATOR SUPPORT SEAL",
            "",
            "   a. Install the upper radiator support seal with the 13 clips."
        ]

    },
    "drive_belt_precaution": {
        "category": "Engine Mechanical",
        "subcategory": "Drive Belts",
        "section": "Drive Belt - Precaution",
        "workflow": [
            "",
            "=== DRIVE BELT - PRECAUTION ===",
            "",
            "NOTE: Do not apply or add any oil or grease to the belt tensioner",
            "to prevent abnormal noises from the belt tensioner pulley, belt",
            "squealing, etc.",
            "",
            "NOTE: Do not allow oil or grease to adhere to the moving parts of",
            "the belt tensioner, as this may cause malfunctions.",
            "",
            "If oil or grease is on the location indicated by the arrow,",
            "replace the belt tensioner."
        ]
    },
    "drive_belt_inspection": {
        "category": "Engine Mechanical",
        "subcategory": "Drive Belts",
        "section": "Drive Belt - On-Vehicle Inspection",
        "tools": ["None"],
        "workflow": [
            "",
            "=== DRIVE BELT - ON-VEHICLE INSPECTION ===",
            "",
            "1. INSPECT FAN AND GENERATOR V BELT",
            "",
            "   a. Check the belt for wear, cracks or other signs of damage.",
            "",
            "   If any of the following defects is found, replace the fan",
            "   and generator V belt:",
            "   - The belt is cracked.",
            "   - The belt is worn out to the extent that the cords are exposed.",
            "   - The belt has chunks missing from the ribs.",
            "",
            "   b. Check that the belt fits properly in the ribbed grooves.",
            "",
            "      *1  CORRECT",
            "      *2  INCORRECT",
            "",
            "   HINT: Check with your hand to confirm that the belt has not",
            "   slipped out of the grooves on the bottom of the pulley. If it",
            "   has slipped out, replace the fan and generator V belt. Install",
            "   a new fan and generator V belt correctly.",
            "",
            "2. INSPECT V-RIBBED BELT TENSIONER ASSEMBLY",
            "",
            "   a. Check that nothing gets caught in the tensioner by turning",
            "      it clockwise and counterclockwise.",
            "   b. If the result is not as specified, replace the tensioner."
        ]
    },
    "drive_belt_removal": {
        "category": "Engine Mechanical",
        "subcategory": "Drive Belts",
        "section": "Drive Belt - Removal",
        "tools": [
            "6 mm (0.236 in.) bar or equivalent"
        ],
        "workflow": [
            "",
            "=== DRIVE BELT - REMOVAL ===",
            "",
            "1. REMOVE FAN AND GENERATOR V BELT",
            "",
            "   a. While turning the belt tensioner counterclockwise, align the",
            "      service hole for the belt tensioner and the belt tensioner",
            "      fixing position.",
            "",
            "   b. Insert a bar of 6 mm (0.236 in.) into the service hole to",
            "      fix the belt tensioner in place.",
            "",
            "   HINT: The pulley bolt for the belt tensioner has a left-hand thread.",
            "",
            "   c. Remove the V belt."
        ]
    },
    "drive_belt_installation": {
        "category": "Engine Mechanical",
        "subcategory": "Drive Belts",
        "section": "Drive Belt - Installation",
        "tools": [
            "6 mm (0.236 in.) bar or equivalent"
        ],
        "workflow": [
            "",
            "=== DRIVE BELT - INSTALLATION ===",
            "",
            "1. INSTALL FAN AND GENERATOR V BELT",
            "",
            "   a. Set the V belt onto every part.",
            "",
            "   Belt Routing:",
            "   *1  Vane Pump",
            "   *2  Water Pump",
            "   *3  No. 2 Idler",
            "   *4  Generator",
            "   *5  Cooler Compressor",
            "   *6  No. 1 Idler",
            "   *7  Crankshaft",
            "   *8  V-ribbed Belt Tensioner",
            "",
            "   b. While turning the belt tensioner counterclockwise, remove",
            "      the pin.",
            "",
            "   NOTE: Make sure that the V belt is properly installed to each",
            "   pulley.",
            "",
            "   c. Check that the belt fits properly in the ribbed grooves.",
            "",
            "   HINT: Make sure to check by hand that the belt has not slipped",
            "   out of the grooves on the bottom of the pulley."
        ]
    },
    "pcv_valve_removal": {
        "category": "Engine Mechanical",
        "subcategory": "PCV System",
        "section": "PCV Valve - Removal",
        "tools": ["Pliers or hose clamp tool"],
        "references": {"v_bank_cover": "V-Bank Cover Removal"},
        "workflow": [
            "",
            "=== PCV VALVE - REMOVAL ===",
            "",
            "1. REMOVE V-BANK COVER",
            "   → Refer to V-Bank Cover Removal",
            "",
            "2. DISCONNECT HEATER HOSE",
            "   a. Disconnect the heater hose clamp.",
            "",
            "3. REMOVE PCV VALVE SUB-ASSEMBLY",
            "   a. Loosen the hose clamp and disconnect the PCV hose from the valve.",
            "   b. Remove the valve."
        ]
    },
    "pcv_valve_inspection": {
        "category": "Engine Mechanical",
        "subcategory": "PCV System",
        "section": "PCV Valve - Inspection",
        "tools": ["Clean hose"],
        "workflow": [
            "",
            "=== PCV VALVE - INSPECTION ===",
            "",
            "1. INSPECT PCV VALVE SUB-ASSEMBLY",
            "",
            "   a. Install a clean hose to the PCV valve.",
            "   b. Check the PCV valve operation.",
            "",
            "   c. Blow air into the cylinder head side, and check that air",
            "      passes through easily.",
            "      *1  Hose    *2  Air",
            "",
            "   ⚠️ WARNING: Do not suck air through the valve.",
            "   Petroleum substances inside the valve are hazardous to your health.",
            "",
            "   d. Blow air into the intake manifold side, and check that air",
            "      passes through with difficulty.",
            "      *1  Hose    *2  Air",
            "",
            "   e. If the result is not as specified, replace the PCV valve.",
            "   f. Remove the clean hose from the PCV valve."
        ]
    },
    "pcv_valve_installation": {
        "category": "Engine Mechanical",
        "subcategory": "PCV System",
        "section": "PCV Valve - Installation",
        "torque": {"pcv_valve": "27 N·m (275 kgf·cm, 20 ft·lbf)"},
        "specs": {"adhesive": "Toyota Genuine Adhesive 1324, Three Bond 1324 or equivalent"},
        "tools": ["Torque wrench", "Pliers or hose clamp tool", "Adhesive (Toyota Genuine 1324 or equivalent)"],
        "references": {"v_bank_cover": "V-Bank Cover Installation"},
        "workflow": [
            "",
            "=== PCV VALVE - INSTALLATION ===",
            "",
            "1. INSTALL PCV VALVE SUB-ASSEMBLY",
            "",
            "   a. Apply adhesive to 2 or 3 threads of the PCV valve.",
            "      Adhesive: Toyota Genuine Adhesive 1324, Three Bond 1324 or equivalent",
            "   b. Install the PCV valve.",
            "      Torque: 27 N·m (275 kgf·cm, 20 ft·lbf)",
            "   c. Connect the PCV hose to the valve.",
            "   d. Secure the hose with the clamp.",
            "",
            "2. CONNECT HEATER HOSE",
            "   a. Connect the heater hose clamp.",
            "",
            "3. INSTALL V-BANK COVER",
            "   → Refer to V-Bank Cover Installation"
        ]
    }
    }