ENGINE_PERFORMANCE = {

    "ignition_inspection": {
        "category": "Engine Performance",
        "subcategory": "Ignition",
        "section": "Ignition System - On-Vehicle Inspection",
        "specs": {
            "spark_plug": {
                "recommended": "DENSO SK16HR11",
                "electrode_gap_new": "1.0 to 1.1 mm (0.0394 to 0.0433 in.)",
                "electrode_gap_max_used": "1.3 mm (0.0512 in.)",
                "insulation_resistance": "10 MΩ or higher"
            }
        },
        "tools": [
            "Spark plug socket",
            "Megohmmeter",
            "Spark plug cleaner",
            "Feeler gauge"
        ],
        "workflow": [
            "",
            "=== IGNITION SYSTEM - ON-VEHICLE INSPECTION ===",
            "",
            "1. PERFORM SPARK TEST",
            "",
            "   a. Check for DTCs.",
            "   NOTE: If any DTC is output, perform the troubleshooting procedures for that DTC.",
            "",
            "   b. Check if sparks occur.",
            "   c. Remove the 6 spark plugs.",
            "   d. Install the spark plug to the ignition coil assembly and connect the",
            "      ignition coil assembly connector.",
            "   e. Disconnect the fuel pump ECU connector.",
            "   f. Ground the spark plug.",
            "   g. Visually check that sparks occur while the engine is being cranked.",
            "",
            "   NOTE: Be sure to ground the spark plug when checking.",
            "   NOTE: Replace the ignition coil assembly if it receives an impact.",
            "   NOTE: Do not crank the engine for more than 2 seconds.",
            "",
            "   h. Check that the ignition coil assembly connector is securely connected.",
            "",
            "   RESULT:",
            "   NG → Connect securely, then retest",
            "   OK → Go to next step",
            "",
            "   i. Perform a spark test on each ignition coil assembly.",
            "   j. If there is a cylinder where sparks do not occur, replace its ignition",
            "      coil assembly with one from a cylinder where sparks occur normally.",
            "   k. Crank the engine and visually check that sparks occur at the cylinder.",
            "",
            "   RESULT:",
            "   OK → Replace ignition coil assembly",
            "   NG → Go to next step",
            "",
            "   l. Inspect the spark plug.",
            "   m. Replace the spark plug with a known good one.",
            "   n. Perform spark test again.",
            "",
            "   RESULT:",
            "   OK → Replace spark plug",
            "   NG → Go to next step",
            "",
            "   o. Check power supply to ignition coil assembly.",
            "      - Turn the ignition switch to ON.",
            "      - Check that there is battery voltage at the ignition coil assembly",
            "        positive (+) terminal.",
            "",
            "   RESULT:",
            "   NG → Check wiring between ignition switch and ignition coil assembly",
            "   OK → Go to next step",
            "",
            "   p. Check the VVT sensor for intake side.",
            "   q. Check the VVT sensor for exhaust side.",
            "   r. Check the crankshaft position sensor.",
            "   s. Install the 6 spark plugs.",
            "   t. Connect the fuel pump ECU connector.",
            "",
            "2. INSPECT SPARK PLUG",
            "",
            "   a. Check the electrode.",
            "   b. Using a megohmmeter, measure the insulation resistance.",
            "",
            "   Standard Insulation Resistance:",
            "   Spark plug (terminal part) - Body ground: 10 MΩ or higher",
            "",
            "   c. If a megohmmeter is not available, perform this simple inspection:",
            "      - Quickly accelerate the engine to 4000 rpm 5 times.",
            "      - Remove the spark plug.",
            "      - Visually check the spark plug.",
            "      - If the electrode is dry, the spark plug is functioning properly.",
            "      - If the electrode is damp, proceed to the next step.",
            "",
            "   d. Check the spark plug for any damage on its threads and insulator.",
            "      - If there is damage, replace the spark plug.",
            "",
            "   Recommended Spark Plug: DENSO SK16HR11",
            "",
            "   e. Clean the spark plugs.",
            "   f. Check the spark plug electrode gap.",
            "",
            "   Maximum electrode gap for used spark plug: 1.3 mm (0.0512 in.)",
            "   If the gap is more than the maximum, replace the spark plug.",
            "",
            "   Electrode gap for new spark plug: 1.0 to 1.1 mm (0.0394 to 0.0433 in.)"
        ]
    }
},
"spark_plug_removal": {
        "category": "Engine Performance",
        "subcategory": "Ignition",
        "section": "Spark Plug - Removal",
        "tools": [
            "Spark plug socket (14 mm)",
            "Socket set",
            "Extensions",
            "Torque wrench"
        ],
        "references": {
            "v_bank_cover": "V-Bank Cover Removal",
            "air_tube": "Air Tube Removal",
            "no1_emission_control_valve": "No. 1 Emission Control Valve Set Removal",
            "no2_air_tube": "No. 2 Air Tube Removal",
            "no2_emission_control_valve": "No. 2 Emission Control Valve Set Removal"
        },
        "workflow": [
            "",
            "=== SPARK PLUG - REMOVAL ===",
            "",
            "1. REMOVE V-BANK COVER",
            "   → Refer to V-Bank Cover Removal",
            "",
            "2. REMOVE AIR CLEANER CAP AND HOSE",
            "",
            "   a. Disconnect the mass air flow meter connector, vacuum hose and",
            "      ventilation hose and detach the 4 clamps.",
            "   b. Loosen the clamp.",
            "   c. Unfasten the 4 hook clamps, and then remove the bolt and air",
            "      cleaner cap and hose.",
            "",
            "3. REMOVE AIR TUBE",
            "   → Refer to Air Tube Removal",
            "",
            "4. REMOVE NO. 1 EMISSION CONTROL VALVE SET",
            "   → Refer to No. 1 Emission Control Valve Set Removal",
            "",
            "5. REMOVE NO. 2 AIR TUBE",
            "   → Refer to No. 2 Air Tube Removal",
            "",
            "6. REMOVE NO. 2 EMISSION CONTROL VALVE SET",
            "   → Refer to No. 2 Emission Control Valve Set Removal",
            "",
            "7. REMOVE IGNITION COIL ASSEMBLY",
            "",
            "   a. Disconnect the 6 ignition coil assembly connectors.",
            "   b. Remove the 6 bolts and 6 ignition coil assemblies.",
            "",
            "8. REMOVE SPARK PLUG",
            "",
            "   a. Remove the 6 spark plugs."
        ]
    },
    
