ENGINE_MECHANICAL = {

    "engine_oil_filter": {
        "category": "Engine Mechanical",
        "subcategory": "Oil & Filter",
        "section": "Engine Oil & Filter Replacement",
        "fluid": {
            "type": "ILSAC multigrade engine oil",
            "viscosity": "0W-20",
            "capacity": {
                "drain_refill_without_filter": "5.7 L (6.0 US qts, 5.0 Imp. qts)",
                "drain_refill_with_filter": "6.2 L (6.6 US qts, 5.5 Imp. qts)",
                "dry_fill": "7.1 L (7.5 US qts, 6.2 Imp. qts)"
            }
        },
        "torque": {
            "oil_pan_drain_plug": "40 N·m (408 kgf·cm, 30 ft·lbf)",
            "oil_filter_cap": "25 N·m (255 kgf·cm, 18 ft·lbf)",
            "oil_filter_drain_plug": "13 N·m (127 kgf·cm, 9 ft·lbf)",
            "engine_under_cover_bolts": "29 N·m (296 kgf·cm, 21 ft·lbf)",
            "front_lower_bumper_cover_bolts": "8.0 N·m (82 kgf·cm, 71 in·lbf)"
        },
        "tools": [
            "SST 09228-06501 (oil filter wrench)",
            "15 mm inside diameter hose",
            "Torque wrench",
            "Socket set",
            "Oil drain pan",
            "Funnel",
            "New gasket (drain plug)",
            "New O-rings (filter cap & drain plug)"
        ],
        "workflow": [
            "",
            "=== ENGINE OIL & FILTER REPLACEMENT ===",
            "",
            "1. REMOVE ENGINE UNDER COVER SEAL",
            "",
            "   a. Remove the 2 bolts and engine under cover seal.",
            "",
            "2. REMOVE COOL AIR INTAKE DUCT (for 4WD with Intuitive Parking Assist System)",
            "",
            "   Refer to procedure for your model year.",
            "",
            "3. DISCONNECT FRONT LOWER BUMPER COVER",
            "",
            "   a. Remove the 2 bolts and clip, and disconnect the front bumper lower cover.",
            "",
            "4. DISCONNECT NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "",
            "   a. Remove the 4 bolts and open the No. 1 engine under cover sub-assembly",
            "      as shown in the illustration.",
            "",
            "5. DRAIN ENGINE OIL",
            "",
            "   a. Remove the oil filler cap.",
            "   b. Remove the oil pan drain plug and drain the engine oil into a container.",
            "   c. Install a new gasket and the oil pan drain plug.",
            "      Torque: 40 N·m (408 kgf·cm, 30 ft·lbf)",
            "",
            "6. REMOVE OIL FILTER ELEMENT",
            "",
            "   a. Connect a hose with an inside diameter of 15 mm (0.591 in.) to the pipe.",
            "",
            "      *1  Pipe",
            "      *2  Hose",
            "",
            "   b. Remove the oil filter drain plug.",
            "",
            "   c. Install the pipe to the oil filter cap.",
            "",
            "      *1  Oil Filter Cap Assembly",
            "      *2  Valve",
            "      *3  Pipe",
            "      *4  O-ring",
            "      *5  Hose",
            "",
            "   NOTE: If the O-ring is removed with the drain plug, install the O-ring",
            "   together with the pipe.",
            "",
            "   HINT: Use a container to catch the draining oil.",
            "",
            "   d. Check that oil is drained from the oil filter. Then, disconnect the pipe",
            "      and remove the O-ring as shown in the illustration.",
            "",
            "   e. Using SST, remove the oil filter cap.",
            "      SST: 09228-06501",
            "",
            "      *1  Oil Filter Bracket Clip",
            "",
            "   NOTE: Do not remove the oil filter bracket clip.",
            "",
            "   f. Remove the oil filter element and O-ring from the oil filter cap.",
            "",
            "      *1  O-ring",
            "",
            "   NOTE: Be sure to remove the O-ring (for the cap) by hand, without using any",
            "   tools, to prevent damage to the groove for the O-ring in the cap.",
            "",
            "7. INSTALL OIL FILTER ELEMENT",
            "",
            "   a. Clean the inside of the oil filter cap, the threads and O-ring groove.",
            "",
            "   b. Apply a small amount of engine oil to a new O-ring and install the O-ring",
            "      to the oil filter cap.",
            "",
            "      *1  O-ring",
            "      *a  CORRECT",
            "      *b  INCORRECT",
            "",
            "   NOTE: Be sure to install the O-ring in the proper location, otherwise oil may leak.",
            "   NOTE: Do not twist the O-ring.",
            "",
            "   c. Set a new oil filter element on the oil filter cap.",
            "",
            "   d. Remove any dirt or foreign matter from the installation surface of the engine.",
            "",
            "   e. Apply a small amount of engine oil to the O-ring again and temporarily install",
            "      the oil filter cap.",
            "",
            "   NOTE: Do not pinch the O-ring for the cap.",
            "",
            "   f. Using SST, tighten the oil filter cap.",
            "      SST: 09228-06501",
            "      Torque: 25 N·m (255 kgf·cm, 18 ft·lbf)",
            "",
            "      *1  Oil Filter Cap Assembly",
            "      *2  O-ring",
            "      *3  Oil Filter Bracket",
            "      *4  Oil Filter Bracket Clip",
            "      *a  No gap",
            "",
            "   NOTE: After tightening the oil filter cap assembly, make sure that there is",
            "   no gap and that the O-ring is not protruding.",
            "   NOTE: When tightening the oil filter cap, do not remove the oil filter bracket clip.",
            "",
            "   g. Apply a small amount of engine oil to a new drain plug O-ring and install",
            "      the O-ring to the oil filter cap.",
            "",
            "      *1  O-Ring",
            "",
            "   NOTE: Before installing the O-ring, remove any dirt or foreign matter from",
            "   the installation surface of the oil filter cap.",
            "",
            "   h. Install the oil filter drain plug.",
            "      Torque: 13 N·m (127 kgf·cm, 9 ft·lbf)",
            "",
            "   NOTE: Make sure that the O-ring does not get caught between the parts.",
            "",
            "8. ADD ENGINE OIL",
            "",
            "   a. Add fresh engine oil.",
            "",
            "   NOTE: Do not allow engine oil to adhere to the moving parts of the belt",
            "   tensioner, as this may cause malfunctions.",
            "   If engine oil is on the location indicated by the arrow, replace the belt",
            "   tensioner.",
            "",
            "   Standard Engine Oil:",
            "   Oil Grade: ILSAC multigrade engine oil",
            "   Oil Viscosity (SAE): 0W-20",
            "",
            "   Standard Oil Capacity:",
            "   Drain and refill without oil filter change:  5.7 L (6.0 US qts, 5.0 Imp. qts)",
            "   Drain and refill with oil filter change:     6.2 L (6.6 US qts, 5.5 Imp. qts)",
            "   Dry fill:                                     7.1 L (7.5 US qts, 6.2 Imp. qts)",
            "",
            "9. CHECK ENGINE OIL LEVEL",
            "",
            "   Refer to Step 2",
            "",
            "10. INSPECT FOR ENGINE OIL LEAK",
            "",
            "   a. Start the engine. Make sure that there are no oil leaks from the area that",
            "      was worked on.",
            "",
            "11. CONNECT NO. 1 ENGINE UNDER COVER SUB-ASSEMBLY",
            "",
            "   a. Close the No. 1 engine under cover sub-assembly with the 4 bolts.",
            "      Torque: 29 N·m (296 kgf·cm, 21 ft·lbf)",
            "",
            "12. CONNECT FRONT LOWER BUMPER COVER",
            "",
            "   a. Connect the front lower bumper cover with the 2 bolts and clip.",
            "      Torque: 8.0 N·m (82 kgf·cm, 71 in·lbf)",
            "",
            "13. INSTALL COOL AIR INTAKE DUCT (for 4WD with Intuitive Parking Assist System)",
            "",
            "   Refer to procedure for your model year.",
            "",
            "14. INSTALL ENGINE UNDER COVER SEAL",
            "",
            "   a. Install the engine under cover seal with the 2 bolts.",
            "      Torque: 29 N·m (296 kgf·cm, 21 ft·lbf)"
        ]
    }
}