STEERING = {

    "power_steering_bleed": {
        "category": "Steering",
        "subcategory": "Power Steering",
        "section": "Bleed Air from Power Steering System",
        "fluid": {
            "type": "ATF DEXRON II or III, or equivalent",
            "temperature_check": "80°C (176°F)",
            "hot_level": "HOT range on reservoir",
            "cold_level": "COLD range on reservoir",
            "max_level_rise": "5.0 mm (0.197 in.)"
        },
        "specs": {
            "standard_fluid_pressure": "8300 to 8800 kPa (84.7 to 89.7 kgf/cm², 1204 to 1276 psi)",
            "max_pressure_difference": "490 kPa (5.0 kgf/cm², 71 psi) or less"
        },
        "tools": [
            "Jack and jack stands",
            "SST 09640-10011",
            "SST 09641-01010",
            "SST 09641-01030",
            "SST 09641-01060"
        ],
        "workflow": [
            "",
            "=== BLEED AIR FROM POWER STEERING SYSTEM ===",
            "",
            "1. Check the fluid level.",
            "2. Jack up the front of the vehicle and support it with stands.",
            "3. Turn the steering wheel.",
            "   a. With the engine stopped, turn the wheel slowly from lock to",
            "      lock several times.",
            "4. Lower the vehicle.",
            "5. Start the engine.",
            "6. Run the engine at idle for a few minutes.",
            "7. Turn the steering wheel.",
            "   a. With the engine idling, turn the wheel to the left or right",
            "      full lock position and keep it there for 2 to 3 seconds.",
            "   b. Turn the wheel to the opposite full lock position and keep",
            "      it there for 2 to 3 seconds.",
            "   c. Repeat several times.",
            "8. Stop the engine.",
            "9. Check for foaming or emulsification.",
            "",
            "   *a  Correct",
            "   *b  Incorrect",
            "",
            "   If the system has to be bled twice specifically because of",
            "   foaming or emulsification, check for fluid leaks in the power",
            "   steering system.",
            "",
            "10. Check the fluid level.",
            "",
            "",
            "=== CHECK POWER STEERING FLUID LEVEL ===",
            "",
            "1. Keep the vehicle horizontal.",
            "2. With the engine stopped, check the fluid level in the reservoir.",
            "3. If necessary, add fluid.",
            "",
            "   Fluid: ATF DEXRON II or III, or equivalent",
            "",
            "   HINT: If the fluid is hot (over 40°C (104°F)), make sure that",
            "   the fluid level is within the HOT range on the reservoir.",
            "   If the fluid is cold, make sure that it is within the COLD range.",
            "",
            "4. Start the engine and run it at idle.",
            "5. Turn the steering wheel from lock to lock several times to",
            "   raise the fluid temperature.",
            "",
            "   Fluid temperature: 80°C (176°F)",
            "",
            "6. Check for foaming or emulsification.",
            "",
            "   *a  Correct",
            "   *b  Incorrect",
            "",
            "   If foaming or emulsification is identified, bleed air from the",
            "   power steering system.",
            "",
            "7. With the engine idling, measure the fluid level in the reservoir.",
            "",
            "   *a  Engine Idling",
            "   *b  Engine Stopped",
            "   *c  5 mm or less",
            "",
            "8. Stop the engine.",
            "9. Wait a few minutes and remeasure the fluid level in the reservoir.",
            "",
            "   Maximum fluid level rise: 5.0 mm (0.197 in.)",
            "",
            "   If the fluid level rise is more than the maximum, bleed air",
            "   from the power steering system.",
            "",
            "10. Check the fluid level.",
            "",
            "",
            "=== CHECK STEERING FLUID PRESSURE ===",
            "",
            "1. Disconnect the pressure feed tube from the vane pump.",
            "2. Connect SST as shown in the illustration.",
            "",
            "   SST: 09640-10011, 09641-01010, 09641-01030, 09641-01060",
            "",
            "   *1  Attachment",
            "   *2  Pressure Feed Tube",
            "   *a  In",
            "   *b  Out",
            "",
            "   NOTE: Check that the valve of SST is in the open position.",
            "",
            "3. Bleed air from the power steering system.",
            "4. Start the engine and run it at idle.",
            "5. Turn the steering wheel from lock to lock several times to",
            "   raise the fluid temperature.",
            "",
            "   Fluid temperature: 80°C (176°F)",
            "",
            "6. With the engine idling, close the valve of SST and observe",
            "   the reading on SST.",
            "",
            "   *1  Power Steering Gear",
            "   *2  Power Steering Fluid Reservoir",
            "   *3  Power Steering Vane Pump",
            "   *a  Valve Closed",
            "",
            "   Standard fluid pressure:",
            "   8300 to 8800 kPa (84.7 to 89.7 kgf/cm², 1204 to 1276 psi)",
            "",
            "   NOTE: Do not keep the valve closed for more than 10 seconds.",
            "   NOTE: Do not allow the fluid temperature to become too high.",
            "",
            "   If the pressure is not within the specified range, check for",
            "   fluid leaks and replace parts as necessary.",
            "",
            "7. With the engine idling, open the valve fully.",
            "",
            "   *1  Power Steering Gear",
            "   *2  Power Steering Fluid Reservoir",
            "   *3  Power Steering Vane Pump",
            "   *a  Valve Open",
            "",
            "8. Measure the fluid pressure at engine speeds of 1000 rpm and",
            "   3000 rpm.",
            "",
            "   Fluid pressure difference: 490 kPa (5.0 kgf/cm², 71 psi) or less",
            "",
            "   NOTE: Do not turn the steering wheel.",
            "",
            "   If the pressure difference is above the specified range, check",
            "   for fluid leaks and replace parts as necessary.",
            "",
            "9. With the engine idling and the valve fully open, turn the",
            "   steering wheel left or right to the full lock position.",
            "   Observe the reading on SST.",
            "",
            "   *1  Power Steering Gear (Lock Position)",
            "   *2  Power Steering Fluid Reservoir",
            "   *3  Power Steering Vane Pump",
            "   *a  Valve Open",
            "",
            "   Standard fluid pressure:",
            "   8300 to 8800 kPa (84.7 to 89.7 kgf/cm², 1204 to 1276 psi)",
            "",
            "   NOTE: Do not keep the steering wheel in the full lock position",
            "   for more than 10 seconds.",
            "   NOTE: Do not allow the fluid temperature to become too high.",
            "",
            "   If the pressure is not within the specified range, check for",
            "   fluid leaks and replace parts as necessary.",
            "",
            "10. Disconnect SST.",
            "11. Connect the pressure feed tube to the vane pump.",
            "12. Bleed air from the power steering system."
        ]
    }
}